---
name: 'App-Util-Conf'
abstract: 'App to register and then find or edit configuration files'
author:
  - 'Adam Marshall'
build_requires:
  Module::Build: '0'
configure_requires:
  Module::Build: '0'
requires:
  Getopt::Long: '2.5'
  Cwd: '0'
  YAML::XS: '0'
dynamic_config: 1
resources:
  repository: https://github.com/ih8celery/App-Util-Conf.git
license: 'MIT'
version: '0.05'

